//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAJESS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_CostCenter
    {
        public int CostCenterAutoId { get; set; }
        public int A_CostCenterId { get; set; }
        public int DebitAccount { get; set; }
        public int CreditAccount { get; set; }
        public string CostCenterName { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Particular { get; set; }
    }
}
