//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAJESS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_GlTransactionDetails
    {
        public long A_GlTransactionDetailsId { get; set; }
        public int A_GlAccountId { get; set; }
        public long A_GlTransactionId { get; set; }
        public decimal DebitAmount { get; set; }
        public decimal CreditAmount { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string ChequeNumber { get; set; }
        public string Particular { get; set; }
    
        public virtual A_GlAccount A_GlAccount { get; set; }
        public virtual A_GlTransaction A_GlTransaction { get; set; }
    }
}
