//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAJESS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int AddressId { get; set; }
        public int DivisionId { get; set; }
        public int DistrictId { get; set; }
        public int ThanaId { get; set; }
        public string Road { get; set; }
        public string Area { get; set; }
        public string Line1 { get; set; }
        public string Line2 { get; set; }
        public string Remarks { get; set; }
    
        public virtual District District { get; set; }
        public virtual Division Division { get; set; }
        public virtual Thana Thana { get; set; }
    }
}
