//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAJESS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyInfo
    {
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public int AddressId { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public System.DateTime CreationDate { get; set; }
        public byte[] Logo { get; set; }
        public string Slogan { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
    }
}
