//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAJESS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierInvestment
    {
        public long SupplierInvestmentId { get; set; }
        public int SupplierId { get; set; }
        public string Reason { get; set; }
        public decimal Amount { get; set; }
        public string MemberName { get; set; }
        public string MemberNid { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<long> A_GlTransactionId { get; set; }
        public int ProcessStatus { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string Particular { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
